# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- release

pool:
  vmImage: ubuntu-latest

variables:
${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
- group: TS.TournamentEngine.Client-Staging
${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
- group: TS.TournamentEngine.Client-Production

steps:
- script: echo $(groupname)
  displayName: 'PrintSourceBranchName'
- task: replacetokens@5
  inputs:
    targetFiles: '**/*.env'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    Contents: 'build/**' # Pull the build directory (React)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'drop' # output artifact named drop
