export const ROUTES = {
    HOME: '/',
    SIGNUP: '/account/signup',
    LOGIN: '/account/login',
    ABOUT: '/about',
    CONTACTS: '/contact-us',
    FORBIDDEN: '/forbidden',
    NOT_FOUND: '/not-found',
    PASSWORD_RESET: '/account/password/reset',
    PASSWORD_SET: '/account/password/set',
    RATING: '/rating',
    SUBMIT_GAME_RESULT: '/result/submit',
    GAME_RESULTS: '/result',
    GAME_RESULT_EDIT: '/result/:id/edit',
    GAME_RESULT_INFO: '/result/:id',
    EDIT_PLAYER: 'account/edit',
};